// !!! This is a file automatically generated by hipify!!!
////////////////////////////////////////////////////////////////////////////////
// GENERATED FILE INFO
//
// Template Source: training/backward/embedding_backward_split_device_kernel_template.cuh
////////////////////////////////////////////////////////////////////////////////



/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// clang-format off

#include "fbgemm_gpu/embedding_backward_template_helpers_hip.cuh"
#include "fbgemm_gpu/utils/tensor_accessor_builder_hip.h"
#include "fbgemm_gpu/split_embeddings_utils_hip.cuh"
#include "fbgemm_gpu/rocm/split_embeddings_common.h"

using namespace fbgemm_gpu;

#if 1
// Buffer load test for WRT4
// #define BUFFER_LOAD_TEST

__device__ uint64_t llvm_amdgcn_raw_buffer_load_fp16x4(int32x4_t srsrc, uint32_t voffset, uint32_t soffset, uint32_t coherency)
    __asm("llvm.amdgcn.raw.buffer.load.i64");

static __device__ void buffer_load_fp16x4(c10::Half* dst, const c10::Half* p_src, int32_t offset){
    int32x4_t res =
        fbgemm_gpu::rocm::amdgcn_make_buffer_resource(p_src);
    *reinterpret_cast<uint64_t*>(&dst[0]) =
        llvm_amdgcn_raw_buffer_load_fp16x4(res, offset * sizeof(uint64_t), 0, 0);
}


template <
    typename grad_t,
    typename cache_t,
    int32_t kFixedMaxVecsPerThread,
    int32_t kThreadGroupSize = kWarpSize,
    int32_t VEC_WIDTH,
    int32_t unrollCount
>
DEVICE_INLINE void compute_grad_sum_weighted_unroll(
    Vec4TAcc<cache_t>* grad_sum,
    const pta::PackedTensorAccessor64<grad_t, 2, at::RestrictPtrTraits>& grad_output,
    const pta::PackedTensorAccessor32<int32_t, 1, at::RestrictPtrTraits>& D_offsets,
    const int32_t D,
    const int32_t T,
    const pta::PackedTensorAccessor32<int32_t, 1, at::RestrictPtrTraits>& sorted_infos,
    const pta::PackedTensorAccessor32<at::acc_type<cache_t, true>, 1, at::RestrictPtrTraits>& sorted_indice_weights,
    const int32_t info_B_num_bits,
    const uint32_t info_B_mask,
    const int32_t segment_start,
    const int32_t sl_start,
    const int32_t sl_end,
    const unsigned int shfl_sync_mask,
    const int32_t vec_start
)
{
    #ifdef BUFFER_LOAD_TEST 
    int32x4_t res =
        fbgemm_gpu::rocm::amdgcn_make_buffer_resource(&grad_output[0][0]);
    #endif

        for (int32_t sl = sl_start; sl < sl_end; sl += kThreadGroupSize) {
            auto sl_j = sl + threadIdx.x;
            const auto b_t = sl_j < sl_end
                ? reinterpret_cast<const uint32_t*>(
                    &sorted_infos[0])[segment_start + sl_j]
                : 0;
            const auto b = b_t & info_B_mask;
            const auto t = b_t >> info_B_num_bits; // if vbe
            int32_t D_start = sl_j < sl_end ? D_offsets[t] : 0; // if vbe // if not nobag

            at::acc_type<cache_t, true> idx_weight = sl_j < sl_end
                ? sorted_indice_weights[segment_start + sl_j]
                : 0.0;
            for (int32_t j = 0; j < kThreadGroupSize/unrollCount && sl+unrollCount*j<sl_end ; ++j) {
                int32_t b_ids[unrollCount];
                int32_t b_startIds[unrollCount];
                at::acc_type<cache_t, true> idx_weight_ids[unrollCount];
                #pragma unroll unrollCount
                for (int32_t i = 0; i < unrollCount; ++i) {
                        int32_t id = unrollCount*j+i;
                        int32_t b_id = SHFL_SYNC(b, id);
                        int32_t D_start_id = SHFL_SYNC(D_start, id);
                        at::acc_type<cache_t, true> idx_weight_id = SHFL_SYNC(idx_weight, id);

                        b_ids[i]=b_id;
                        b_startIds[i]=D_start_id;
                        idx_weight_ids[i]=idx_weight_id;
                }
                for (int32_t vec = 0; vec < kFixedMaxVecsPerThread && (((vec + vec_start) * kThreadGroupSize + threadIdx.x) * VEC_WIDTH)<D; ++vec) {
                    const int32_t d = (((vec + vec_start) * kThreadGroupSize + threadIdx.x) * VEC_WIDTH);
                    #pragma unroll unrollCount
                    for (int32_t i = 0; i < unrollCount; ++i) {
                        #ifdef BUFFER_LOAD_TEST 
                        if constexpr(std::is_same<grad_t, c10::Half>::value){
                            grad_t dst[VEC_WIDTH];
                            const int32_t offset = (b_ids[i]*3840 + b_startIds[i]) *sizeof(half)+((vec + vec_start) * kThreadGroupSize + threadIdx.x)*sizeof(uint64_t);
                            constexpr bool nt_mode = false;
                            *reinterpret_cast<uint64_t*>(&dst[0]) = llvm_amdgcn_raw_buffer_load_fp16x4(res, offset , 0, nt_mode ? 2 : 0);
                            Vec4TAcc<grad_t> grad_out_vec(dst);
                            grad_sum[vec].fma_(grad_out_vec, idx_weight_ids[i]);
                        }
                        #else
                            Vec4TAcc<grad_t> grad_out_vec(
                                &grad_output[b_ids[i]][0] + b_startIds[i] + d // if nobag
                            );
                            grad_sum[vec].fma_(grad_out_vec, idx_weight_ids[i]);
                        #endif
                        
                    }
                }
        }
    }
}


template <
    typename grad_t,
    typename cache_t,
    int32_t kFixedMaxVecsPerThread,
    int32_t kThreadGroupSize = kWarpSize,
    int32_t VEC_WIDTH,
    bool kUseVecBlocking
>
DEVICE_INLINE void compute_grad_sum_weighted(
    Vec4TAcc<cache_t>* grad_sum,
    Vec4TAcc<cache_t>* smem_grad_sum,
    const pta::PackedTensorAccessor64<grad_t, 2, at::RestrictPtrTraits>& grad_output,
    const pta::PackedTensorAccessor32<int32_t, 1, at::RestrictPtrTraits>& D_offsets,
    const int32_t D,
    const int32_t T,
    const pta::PackedTensorAccessor32<int32_t, 1, at::RestrictPtrTraits>& sorted_infos,
    const pta::PackedTensorAccessor32<at::acc_type<cache_t, true>, 1, at::RestrictPtrTraits>& sorted_indice_weights,
    const int32_t info_B_num_bits,
    const uint32_t info_B_mask,
    const int32_t segment_start,
    const int32_t sl_start,
    const int32_t sl_end,
    const unsigned int shfl_sync_mask,
    const int32_t num_vecs
) {
    // Copy value to vecs to make num_vecs known at compile time when
    // kUseVecBlocking == false
    const int32_t vecs = kUseVecBlocking ? num_vecs : kFixedMaxVecsPerThread;
    for (int32_t vec_start = 0;
         vec_start < vecs;
         vec_start += kFixedMaxVecsPerThread) {

        // Reset grad_sum vectors
        #pragma unroll kFixedMaxVecsPerThread
        for (int32_t vec = 0; vec < kFixedMaxVecsPerThread; vec++) {
            grad_sum[vec].acc.x = 0;
            grad_sum[vec].acc.y = 0;
            grad_sum[vec].acc.z = 0;
            grad_sum[vec].acc.w = 0;
        }

        int32_t sl_length = sl_end - sl_start;
        // if (threadIdx.x == 0){
        //     printf("sl_length = %d \n",sl_length);
        // }
        const int32_t unroll_factors[] = {8};//{8, 4, 2};
        const size_t num_factors = sizeof(unroll_factors) / sizeof(unroll_factors[0]);
        int32_t start[num_factors], end[num_factors];
        // Calculate start and end indices
        int32_t prev_end = sl_start;
        for (int i = 0; i < num_factors; ++i) {
            start[i] = prev_end;
            end[i] = sl_end - sl_length % unroll_factors[i];
            prev_end = end[i];
        }

         // Lambda for unroll call
        auto call_unroll = [&](int unroll, int sl_start, int sl_end) {
            switch (unroll) {
                // case 16:
                //     compute_grad_sum_weighted_unroll<grad_t,cache_t,kFixedMaxVecsPerThread,kThreadGroupSize,VEC_WIDTH,16>(
                //         grad_sum, grad_output, D_offsets, D, T, sorted_infos,sorted_indice_weights, info_B_num_bits, info_B_mask,
                //         segment_start, sl_start, sl_end, shfl_sync_mask, vec_start
                //     );
                //     break;
                case 8:
                    compute_grad_sum_weighted_unroll<grad_t,cache_t,kFixedMaxVecsPerThread,kThreadGroupSize,VEC_WIDTH,8>(
                        grad_sum, grad_output, D_offsets, D, T, sorted_infos,sorted_indice_weights, info_B_num_bits, info_B_mask,
                        segment_start, sl_start, sl_end, shfl_sync_mask, vec_start
                    );
                    break;
                // case 4:
                //     compute_grad_sum_weighted_unroll<grad_t,cache_t,kFixedMaxVecsPerThread,kThreadGroupSize,VEC_WIDTH,4>(
                //         grad_sum, grad_output, D_offsets, D, T, sorted_infos,sorted_indice_weights, info_B_num_bits, info_B_mask,
                //         segment_start, sl_start, sl_end, shfl_sync_mask, vec_start
                //     );
                //     break;
                // case 2:
                //     compute_grad_sum_weighted_unroll<grad_t,cache_t,kFixedMaxVecsPerThread,kThreadGroupSize,VEC_WIDTH,2>(
                //         grad_sum, grad_output, D_offsets, D, T, sorted_infos,sorted_indice_weights, info_B_num_bits, info_B_mask,
                //         segment_start, sl_start, sl_end, shfl_sync_mask, vec_start
                //     );
                //     break;
                case 1:
                    compute_grad_sum_weighted_unroll<grad_t,cache_t,kFixedMaxVecsPerThread,kThreadGroupSize,VEC_WIDTH,1>(
                        grad_sum, grad_output, D_offsets, D, T, sorted_infos,sorted_indice_weights, info_B_num_bits, info_B_mask,
                        segment_start, sl_start, sl_end, shfl_sync_mask, vec_start
                    );
                    break;
            }
        };

        for (int i = 0; i < num_factors; ++i) {
            call_unroll(unroll_factors[i], start[i], end[i]);
        }
       
        call_unroll(1, end[num_factors-1], sl_end);

        if (smem_grad_sum) {
            // Store grad_sum in smem_grad_sum
            #pragma unroll kFixedMaxVecsPerThread
            for (int32_t vec = 0;
                 (vec < kFixedMaxVecsPerThread) && ((vec + vec_start) * kThreadGroupSize + threadIdx.x) * VEC_WIDTH < D;
                 ++vec) {
                const int32_t d_vec = ((vec + vec_start) * kThreadGroupSize + threadIdx.x);
                smem_grad_sum[d_vec] = grad_sum[vec];
            }
        }
    }
}
#else 
template <
    typename grad_t,
    typename cache_t,
    int32_t kFixedMaxVecsPerThread,
    int32_t kThreadGroupSize = kWarpSize,
    int32_t VEC_WIDTH,
    bool kUseVecBlocking
>
DEVICE_INLINE void compute_grad_sum_weighted(
    Vec4TAcc<cache_t>* grad_sum,
    Vec4TAcc<cache_t>* smem_grad_sum,
    const pta::PackedTensorAccessor64<grad_t, 2, at::RestrictPtrTraits>& grad_output,
    const pta::PackedTensorAccessor32<int32_t, 1, at::RestrictPtrTraits>& D_offsets,
    const int32_t D,
    const int32_t T,
    const pta::PackedTensorAccessor32<int32_t, 1, at::RestrictPtrTraits>& sorted_infos,
    const pta::PackedTensorAccessor32<at::acc_type<cache_t, true>, 1, at::RestrictPtrTraits>& sorted_indice_weights,
    const int32_t info_B_num_bits,
    const uint32_t info_B_mask,
    const int32_t segment_start,
    const int32_t sl_start,
    const int32_t sl_end,
    const unsigned int shfl_sync_mask,
    const int32_t num_vecs
) {
    // Copy value to vecs to make num_vecs known at compile time when
    // kUseVecBlocking == false
    const int32_t vecs = kUseVecBlocking ? num_vecs : kFixedMaxVecsPerThread;
    for (int32_t vec_start = 0;
         vec_start < vecs;
         vec_start += kFixedMaxVecsPerThread) {

        // Reset grad_sum vectors
        #pragma unroll kFixedMaxVecsPerThread
        for (int32_t vec = 0; vec < kFixedMaxVecsPerThread; vec++) {
            grad_sum[vec].acc.x = 0;
            grad_sum[vec].acc.y = 0;
            grad_sum[vec].acc.z = 0;
            grad_sum[vec].acc.w = 0;
        }

        for (int32_t sl = sl_start; sl < sl_end; sl += kThreadGroupSize) {
            auto sl_j = sl + threadIdx.x;
            const auto b_t = sl_j < sl_end
                ? reinterpret_cast<const uint32_t*>(
                    &sorted_infos[0])[segment_start + sl_j]
                : 0;
            const auto b = b_t & info_B_mask;
            const auto t = b_t >> info_B_num_bits; // if vbe
            int32_t D_start = sl_j < sl_end ? D_offsets[t] : 0; // if vbe // if not nobag
            at::acc_type<cache_t, true> idx_weight = sl_j < sl_end
                ? sorted_indice_weights[segment_start + sl_j]
                : 0.0;
            #pragma unroll kThreadGroupSize
            for (int32_t j = 0; j < kThreadGroupSize && sl + j < sl_end; ++j) {
                int32_t b_j = SHFL_SYNC(b, j);
                int32_t D_start_j = SHFL_SYNC(D_start, j);
                at::acc_type<cache_t, true> idx_weight_j = SHFL_SYNC(idx_weight, j);

                #pragma unroll kFixedMaxVecsPerThread
                for (int32_t vec = 0; vec < kFixedMaxVecsPerThread && (((vec + vec_start) * kThreadGroupSize + threadIdx.x) * VEC_WIDTH) < D; ++vec) {
                    const int32_t d = (((vec + vec_start) * kThreadGroupSize + threadIdx.x) * VEC_WIDTH);
                    Vec4TAcc<grad_t> grad_out_vec(
                        &grad_output[b_j][0] + D_start_j + d // if nobag
                    );
                    grad_sum[vec].fma_(grad_out_vec, idx_weight_j);
                }
            }
        }

        if (smem_grad_sum) {
            // Store grad_sum in smem_grad_sum
            #pragma unroll kFixedMaxVecsPerThread
            for (int32_t vec = 0;
                 (vec < kFixedMaxVecsPerThread) && ((vec + vec_start) * kThreadGroupSize + threadIdx.x) * VEC_WIDTH < D;
                 ++vec) {
                const int32_t d_vec = ((vec + vec_start) * kThreadGroupSize + threadIdx.x);
                smem_grad_sum[d_vec] = grad_sum[vec];
            }
        }
    }
}
#endif

    // clang-format on